// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poker.API.DbContexts;

namespace Poker.API.Migrations
{
    [DbContext(typeof(PokerHandsContext))]
    partial class PokerHandsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poker.API.DataObjects.Entities.PokerHand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Card1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PokerHands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9ff5f60-3500-4311-bdac-3faacdeb92b1"),
                            Card1 = "AH",
                            Card2 = "AS",
                            Card3 = "AD",
                            Card4 = "AC",
                            Card5 = "2H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 193, DateTimeKind.Unspecified).AddTicks(4585), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Berry",
                            Type = "Four of a Kind"
                        },
                        new
                        {
                            Id = new Guid("8d6e84de-47ce-4561-9a41-5215eb26526b"),
                            Card1 = "KC",
                            Card2 = "2C",
                            Card3 = "3C",
                            Card4 = "4C",
                            Card5 = "8C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(4882), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Jerry",
                            Type = "Flush"
                        },
                        new
                        {
                            Id = new Guid("7d6e84de-47ce-4561-9a41-5215eb26526b"),
                            Card1 = "KH",
                            Card2 = "2H",
                            Card3 = "3H",
                            Card4 = "4H",
                            Card5 = "9H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(4964), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Jerry",
                            Type = "Flush"
                        },
                        new
                        {
                            Id = new Guid("6d6e84de-47ce-4561-9a41-5215eb26526b"),
                            Card1 = "QC",
                            Card2 = "2D",
                            Card3 = "7C",
                            Card4 = "5S",
                            Card5 = "5H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(4976), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Jerry",
                            Type = "Pair"
                        },
                        new
                        {
                            Id = new Guid("5832f956-2600-4175-b8f3-7f1df28d8b16"),
                            Card1 = "2D",
                            Card2 = "7H",
                            Card3 = "6H",
                            Card4 = "QS",
                            Card5 = "4H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6272), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Daniel Negranu",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("45aa9d27-16f2-4a81-9528-06fc6393ee5b"),
                            Card1 = "2S",
                            Card2 = "7C",
                            Card3 = "6S",
                            Card4 = "QD",
                            Card5 = "4C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6311), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("18888494-243a-4293-b1b2-364c5fade6fa"),
                            Card1 = "3H",
                            Card2 = "7D",
                            Card3 = "6D",
                            Card4 = "QC",
                            Card5 = "4S",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6322), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Tony G",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("4d42a8e7-c322-4dd5-9b0e-444600da70d4"),
                            Card1 = "AH",
                            Card2 = "KH",
                            Card3 = "10H",
                            Card4 = "JH",
                            Card5 = "QH",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6329), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "Straight Flush"
                        },
                        new
                        {
                            Id = new Guid("9051d0d7-6a10-4c23-8b67-1f48fe798a1d"),
                            Card1 = "2H",
                            Card2 = "6H",
                            Card3 = "3D",
                            Card4 = "4S",
                            Card5 = "5H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6335), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Daniel Negranu",
                            Type = "Straight"
                        },
                        new
                        {
                            Id = new Guid("82029ec5-4331-44f3-b73f-8ecc10826b92"),
                            Card1 = "2D",
                            Card2 = "7H",
                            Card3 = "6H",
                            Card4 = "QS",
                            Card5 = "4H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6342), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Daniel Negranu",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("55744fa9-4334-4e2e-a1ff-70360dd025f7"),
                            Card1 = "2S",
                            Card2 = "7C",
                            Card3 = "6S",
                            Card4 = "QD",
                            Card5 = "4C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6349), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("659cf963-4dbd-4053-834f-440ccc402095"),
                            Card1 = "2H",
                            Card2 = "7D",
                            Card3 = "6D",
                            Card4 = "QC",
                            Card5 = "4S",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6355), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Tony G",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("a9118362-fb36-4b8a-a657-4d28d673a593"),
                            Card1 = "2D",
                            Card2 = "7H",
                            Card3 = "6H",
                            Card4 = "10D",
                            Card5 = "4H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6361), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Daniel Negranu",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("5c06ab27-125f-4a9c-aa0a-f1695aef4271"),
                            Card1 = "2S",
                            Card2 = "7C",
                            Card3 = "6S",
                            Card4 = "QD",
                            Card5 = "4C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6368), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("28da5c8d-1577-4bd5-9210-73f859fd8533"),
                            Card1 = "2H",
                            Card2 = "7D",
                            Card3 = "6D",
                            Card4 = "QC",
                            Card5 = "4S",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6374), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Tony G",
                            Type = "High Card"
                        },
                        new
                        {
                            Id = new Guid("ab28069b-97a6-408d-afee-81faf0360427"),
                            Card1 = "2D",
                            Card2 = "2H",
                            Card3 = "2D",
                            Card4 = "10D",
                            Card5 = "10H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6380), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Daniel Negranu",
                            Type = "Full House"
                        },
                        new
                        {
                            Id = new Guid("9611fc8d-956e-462a-b1b7-1c30f6cc601d"),
                            Card1 = "4S",
                            Card2 = "4C",
                            Card3 = "4D",
                            Card4 = "QD",
                            Card5 = "5C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6387), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "Three of a Kind"
                        },
                        new
                        {
                            Id = new Guid("93767f99-7c0a-44af-9930-93ad5e323021"),
                            Card1 = "8H",
                            Card2 = "8D",
                            Card3 = "9D",
                            Card4 = "9C",
                            Card5 = "6H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6393), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Tony G",
                            Type = "Two Pair"
                        },
                        new
                        {
                            Id = new Guid("655861ee-8a2d-4e8b-9d43-34b050150f11"),
                            Card1 = "4S",
                            Card2 = "4C",
                            Card3 = "6S",
                            Card4 = "QD",
                            Card5 = "5C",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6399), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Phil Hellmuth",
                            Type = "Pair"
                        },
                        new
                        {
                            Id = new Guid("5a8222f5-114a-4fd0-b7fb-f28b40796b2e"),
                            Card1 = "2H",
                            Card2 = "8D",
                            Card3 = "9D",
                            Card4 = "10C",
                            Card5 = "8H",
                            DateCreated = new DateTimeOffset(new DateTime(2021, 3, 28, 21, 45, 29, 195, DateTimeKind.Unspecified).AddTicks(6406), new TimeSpan(0, -4, 0, 0, 0)),
                            PlayerName = "Tony G",
                            Type = "Pair"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
